# Generated by Django 6.1.2 on 2026-10-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('away_message', models.TextField(default='Admin is currently offline. Automated assistant is responding to customer inquiries.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Availability Setting',
                'verbose_name_plural': 'Admin Availability Settings',
            },
        ),
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('bot_response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('responded', 'Responded'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Inquiry',
                'verbose_name_plural': 'Customer Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
