# Generated by Django 6.1.2 on 2026-10-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_adminavailability_customerinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=64, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=50)),
                ('shipping_address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='adminavailability',
            options={'verbose_name': 'Admin Availability & Alerts Setting', 'verbose_name_plural': 'Admin Availability & Alerts Settings'},
        ),
        migrations.AddField(
            model_name='adminavailability',
            name='admin_email',
            field=models.EmailField(default='admin@jirmassplastics.com', max_length=254),
        ),
        migrations.AddField(
            model_name='adminavailability',
            name='email_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminavailability',
            name='webhook_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminavailability',
            name='webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
