# Generated by Django 6.1.2 on 2026-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_alter_adminavailability_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Primary Brand Customization', max_length=100)),
                ('logo', models.FileField(blank=True, help_text='Upload your company logo (SVG, PNG, JPG, or WEBP)', null=True, upload_to='brand/')),
                ('hero_background', models.FileField(blank=True, help_text='Upload hero banner background graphic (SVG, JPG, PNG, or WEBP)', null=True, upload_to='brand/')),
                ('favicon', models.FileField(blank=True, help_text='Upload browser favicon (SVG, ICO, or PNG)', null=True, upload_to='brand/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Graphic & Asset Customization',
                'verbose_name_plural': 'Brand Graphic & Asset Customizations',
            },
        ),
    ]
